### PR TITLE
Styles front and back

### PR DESCRIPTION
**Pull request by nealfennimore**
Adds in webpack config for style extraction for backend and frontend styles

### CODE REVIEW

**Comment by mitogh** [comment]
I see, asking because now the BE has some FE so `FE` is no longer just the `FE` views is also part of the BE 😆

**Comment by mitogh** [comment]
:turkey-dance:

**Comment by mitogh** [comment]
Shall we remove this branch as well @nealfennimore ?

**Comment by nealfennimore** [comment]
It's :boom:

**Pull request merged**
